### ISSUE TITLE
Pipeline crash

### ISSUE THREAD

**Issue by JeffBolle** [logstash-plugins/logstash-filter-kv#56]
When running the KV filter against some particularly nasty data, we are able to crash the pipeline:

```
Exception in thread "Ruby-0-Thread-13@[main]>worker5: /usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:384" java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:422)
	at java.util.ArrayList.remove(ArrayList.java:499)
	at org.logstash.FieldReference.parse(FieldReference.java:167)
	at org.logstash.FieldReference.parseToCache(FieldReference.java:142)
	at org.logstash.FieldReference.from(FieldReference.java:74)
	at org.logstash.ConvertedMap.convertKey(ConvertedMap.java:101)
	at org.logstash.ConvertedMap.access$000(ConvertedMap.java:23)
	at org.logstash.ConvertedMap$1.visit(ConvertedMap.java:34)
	at org.logstash.ConvertedMap$1.visit(ConvertedMap.java:28)
	at org.jruby.RubyHash.visitLimited(RubyHash.java:662)
	at org.jruby.RubyHash.visitAll(RubyHash.java:647)
	at org.logstash.ConvertedMap.newFromRubyHash(ConvertedMap.java:68)
	at org.logstash.ConvertedMap.newFromRubyHash(ConvertedMap.java:63)
	at org.logstash.Valuefier.lambda$initConverters$11(Valuefier.java:142)
	at org.logstash.Valuefier.convert(Valuefier.java:73)
	at org.logstash.ext.JrubyEventExtLibrary$RubyEvent.ruby_set_field(JrubyEventExtLibrary.java:95)
	at org.logstash.ext.JrubyEventExtLibrary$RubyEvent$INVOKER$i$2$0$ruby_set_field.call(JrubyEventExtLibrary$RubyEvent$INVOKER$i$2$0$ruby_set_field.gen)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:358)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:195)
	at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:323)
	at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
	at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:83)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:179)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:165)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:348)
	at org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:173)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:177)
	at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:332)
	at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
	at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:83)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:179)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:165)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:348)
	at org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:173)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:177)
	at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:332)
	at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
	at org.jruby.ir.interpreter.Interpreter.INTERPRET_BLOCK(Interpreter.java:132)
	at org.jruby.runtime.MixedModeIRBlockBody.commonYieldPath(MixedModeIRBlockBody.java:148)
	at org.jruby.runtime.IRBlockBody.doYield(IRBlockBody.java:186)
	at org.jruby.runtime.BlockBody.yield(BlockBody.java:116)
	at org.jruby.runtime.Block.yield(Block.java:165)
	at org.jruby.RubyArray.each(RubyArray.java:1734)
	at org.jruby.RubyArray$INVOKER$i$0$0$each.call(RubyArray$INVOKER$i$0$0$each.gen)
	at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodZeroBlock.call(JavaMethod.java:498)
	at org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:77)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:83)
	at org.jruby.ir.instructions.CallBase.interpret(CallBase.java:428)
	at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:355)
	at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
	at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:83)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:179)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:165)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:200)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:338)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:163)
	at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:314)
	at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
	at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:83)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:179)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:165)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:200)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:338)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:163)
	at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:314)
	at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
	at org.jruby.ir.interpreter.Interpreter.INTERPRET_BLOCK(Interpreter.java:132)
	at org.jruby.runtime.MixedModeIRBlockBody.commonYieldPath(MixedModeIRBlockBody.java:148)
	at org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:73)
	at org.jruby.runtime.Block.call(Block.java:124)
	at org.jruby.RubyProc.call(RubyProc.java:289)
	at org.jruby.internal.runtime.methods.ProcMethod.call(ProcMethod.java:63)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:204)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:200)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:338)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:163)
	at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:314)
	at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
	at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:83)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:179)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:165)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:200)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:338)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:163)
	at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:314)
	at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
	at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:89)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:214)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:200)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:208)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:193)
	at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:323)
	at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
	at org.jruby.ir.interpreter.Interpreter.INTERPRET_BLOCK(Interpreter.java:132)
	at org.jruby.runtime.MixedModeIRBlockBody.commonYieldPath(MixedModeIRBlockBody.java:148)
	at org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:73)
	at org.jruby.runtime.Block.call(Block.java:124)
	at org.jruby.RubyProc.call(RubyProc.java:289)
	at org.jruby.RubyProc.call(RubyProc.java:246)
	at org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:104)
	at java.lang.Thread.run(Thread.java:748)
```

- Version: logstash 6.2.2, kv 4.1.0
- Operating System: Linux  4.13.0-36-generic #40-Ubuntu SMP Fri Feb 16 20:07:48 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Config File (if you have sensitive info, please remove it): 
```input { stdin {} }
filter {
  base64 {
    action => "decode"
    field => "message"
  }
  kv {
    recursive => "false"
    source => "message"
    target => "kv"
    transform_key => "lowercase"
    value_split => "="
    field_split => "&?"
    trim_key => " \n\r\t"
  }
}
output { stdout {codec => rubydebug} }
```
- Sample Data: The data below is base64 encoded the config above uses the base64 plugin to decode it. 
```REI+Sy5paSlGIjUrISdqNW5yWWEmZVdeRltXbS1sTzJbO1U8PyxfIk9MRT9qRFZGQDJRKFlHZ0w2T09gZWVNQ1JjOmN9MHZjPih6JU5WeCUxZHJCNXQ2ODs9dF1RbkUyQH4nMTY0SWd+IEl5XiQ4TmA4K1gncz5uYUM8YGJsQDxtbyVAeVtzckEhQzQyX3Q9T1ZSdSZxfSkqMFZXaE43TjtvQyIoM3VDIHVDIGIzLSsqcWt9NTp3JTdeYHEvWXU4QVh4TmdeZV5ifCQlImx+MjBMe3JLe2R5VWYgQDI2LT5TLU9OUSR3fidjPktoPnEwQDd9JTVGI3l7T3c4OU1yK2d+UjQgU01AelkqYncncnxCQT1jPmk2PEJ1T3BjfjZmOD17NFxLJDhOJCNQI2h1WFtKX1NbOlhjQkcyTU11aVFvLCxgTT8vUXNOa1thSDFVNTZXJkJkJGdDKkxAXEdDVDggJnJhKClOIGQzaSA7YD95PVlBYSE8cFd4M188dFBOTit6O0tMMVZHQEAuOzlKbSx9PSh3Z1prQWRmLUkoXy1lQ0goL1tnfXdnYSctUDliNVQjbF1ZOX0/QiE4SmQraXJKWDJaKm4gX31zMntJfiBTJVIkVnNwK25EJ3JOYSYmQSRFZ35dfTleRmR9KS4zIzh1QlxUIDgmQ0x8WklrNndcViNjaCZ4JEhSUWRkLG93K2Jee2MmYz9+PGNrNW9IJGlYVkF7bm1iZE9cfEgyb3gpJD9MRUc+MXJ0IjZ7IUh8WidAJ0ZtVTNsLyNxenMzeGtpMU5cVTF4fCs/amUxKXd8fG4xJS9+PkYlYk5hb2svUGk0c2w+VjcjMSNfIlBIVz00IC1YdFVyfmhzdjlwS2J1NS85eEEoWTUyKWVOQEgoNmBoSnU1JE1xTTgrdkZZN2MuYilqTkxITHZCUiM9aEtGIG83L2A0clhzOXteekxDTH44OjFpU01KfmNzOXY+MC83OiFcRj8kIzFsWzVyZV5hdUZAImBhcDh+cWQwIFJHMmhffDs9fUBdR0w3V15JOkMzbEc7VSd5MjhTTjtOJW0hUXFEPExcRHJJVDs/ZGlcfXh1OS5HYUAhZ0JfSGtLIEAieC1YMzZ0TEhgQWFhVXBCdyR9U0VIN3NtPDQqeHE4aCZjemUqfWsuS1I0PVthbzQ+LVJjM2NuS1xXMl1NREo0Uzg1PkQwVTloWlIpaF5ec35hUnl5KFIpfj4zNWtnNEczdF1DXWlAI28kbHRuTicjOlkgXmY2OzYkYF5baXw6Lj9vR0BiY1hqRlRkI25HPj1nMnA+NHhDVkJlTj5uLDZeTkFVYzpSakZPOlk4QFdZQFghT2NTPT9FUzhDRzFTIz4wZEY/PDR8TzM0dW8wLX5RIll1SDxkVmxhVzJwbTgjN2x6PD5NVT5Cc2F8VypAaTxPRF8rPltrW3IlN0JbVWwqXl5Ae2xzL3VRfWJ+T1U1cVF8fHkiI0deX3xNPFlBdFZBY0U6dVs7fWE4c1BQT05gV3s3I1hKQil2VWcscVc/NCJdXFBeLUNbejhFUiZnZSZbPUJ1PHFcczw+JEJ6NFR8RGNSZGNVQn5oLiNlTk8hR2twSGNQXiZ4bVJMXEghPUErIzZwfWx9N0ZqZj1ILEpwe35IWS0vRCs/M1cxPFpzSzVuT0w5Im4oTXNkMj8kPH4vOXc1T1gqckteRUtfWC1eL0wqN2pVKXEkRzRUMHR+IzU4KXkgVCRgMEheLzlRRWxUXGAmPDZAKXcuRX1uMUxTPTNoQkJmPHFCUFgxVkBRSntTflVAJ2ViIDV+WFNfVmQoQG8gQFBFLXNRUSQsPSJ9aHcwRGloWCo7MCFoX1B5UCtGaTkpJ0siSTxgKXhgTCJvdTg5aihNLis2dWxpSjRYIUNUPUJsSjpJaWhfVCo5IlJnZjR1Q3p8fUhzLl4pdF4qVXAzdm53SlJ1Q0BZeE5pYUU3IVcnT2hccVZlLVhUMkdAeSlhe09DTF0wbDxTQkNHZysoVl9tI0sse3VsYEdwQnwzMz5cWyx1fSFAOC87aS9EW0tSXTxRZDhIVG47YDM+SCVNb017NyFqPS1QRys4O3lrN0EqSCBBSyAgICAgICAgICAgICAgICAgICAgICAgIA==```
- Steps to Reproduce:
0. Install the base64 plugin
1. Run logstash with above config
2. Send provided base64 blob to logstash.
3. Enjoy your stacktrace.

**Comment by yaauie** [comment]
I've filed a bug upstream on logstash-core, which should _not_ crash in this manner when encountering an invalid field name: https://github.com/elastic/logstash/issues/9524

**Comment by JeffBolle** [comment]
Awesome. Thank you. I'm glad to see it getting some attention.

**Comment by yaauie** [comment]
Additionally, in releases >= 4.2.0 of this plugin, we catch runtime exceptions and prevent them from crashing the pipeline.

I'm closing as resolved.
